server:
  port: 8080

spring:
  application:
    name: api-passenger
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30
